version: '3.9'

services:
  user-service:
    build: ./UserService
    container_name: user_service
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=${MONGODB_URI}

  news-aggregator-service:
    build: ./NewsAggregatorService
    container_name: news_aggregator_service
    ports:
      - "8001:8001"
    environment:
      - NEWS_API_KEY=${NEWS_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  notification-service:
    build: ./NotificationService
    container_name: notification_service
    ports:
      - "8002:8002"
    environment:
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
