version: '3.8'
services:
  user-service:
    build: .
    container_name: user_service
    ports:
      - "8001:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=${MONGODB_URI}

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
